version: "3.8"

services:
    wikifeet-nuxt:
        build:
            context: .
            dockerfile: Dockerfile
        image: maticbabnik/wikifeet-nuxt:latest
        ports:
            - "3000:3000"
        restart: unless-stopped
